### PR TITLE
make logging explicit and fix a function

### PR DESCRIPTION
**Pull request by sunayana**
- makes RICHDEM_LOGGING flag explicit in CMakeLists.txt
- fixes assert in FM_OCallaghan template function.

### CODE REVIEW

**Comment by r-barnes** [comment]
The assertion doesn't look it needed fixing. I've incorporated the cmake change. I wasn't able to take the PR directly because of the blast radius on the whitespace.

**Comment by r-barnes** [comment]
My bad. I've fixed the assertion in `FM_OCallaghan` now - thanks!

**Comment by sunayana** [comment]
Thanks @r-barnes. Also to let you know we used richdem in Cervest and created a Julia wrapper for your code, here is a link to the fork:
https://github.com/Cervest/richdem
and the Julia wrapper is here:
https://github.com/Cervest/richdem/tree/master/wrappers/RichDEM.jl

**Comment by r-barnes** [comment]
@sunayana - Cool! Would you be interested in trying to merge that all upstream? I can get you some collaborator access to the repo if that's helpful.

**Comment by sunayana** [comment]
@r-barnes - Yes I would be happy to push the changes upstream if you would give me collaborator access to the repo. Thanks!

**Comment by sunayana** [comment]
> @sunayana - Cool! Would you be interested in trying to merge that all upstream? I can get you some collaborator access to the repo if that's helpful.

@r-barnes I would be happy to merge the changes upstream if you can get me collaborator access to the repo. Thanks!

**Pull request closed without merging**
